# Generated by Django 4.2.7 on 2023-11-12 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_usermodel_condition_remove_usermodel_course_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='name',
            new_name='NameField',
        ),
        migrations.RenameField(
            model_name='usermodel',
            old_name='phone',
            new_name='PhoneField',
        ),
        migrations.RenameField(
            model_name='usermodel',
            old_name='telegram',
            new_name='TelegramField',
        ),
        migrations.RenameField(
            model_name='usermodel',
            old_name='bio',
            new_name='TextField',
        ),
    ]
